version: '3'
services:
  DB:
    hostname: nest-template
    image: postgres:13-alpine
    container_name: template-DB
    networks:
      - template-network
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - './db:/data/db'
    environment:
      - POSTGRES_DB=ecTestDB
      - POSTGRES_USER=ecTestUser
      - POSTGRES_PASSWORD=q1w2e3
    volumes:
      - ./database:/var/lib/postgresql/data
  redis:
    hostname: nest-template
    image: redis:6-alpine
    container_name: template-redis
    networks:
      - template-network
    restart: on-failure
    ports:
      - 6379:6379

networks:
  template-network:
